
CC	= g++

LINK= g++

CINCPATHFLAGS = -Iincludes\
				-Imain\
				-Isrc\
                -I/home/xin/ArenaSDK_Linux_x64/include/Arena\
				-I/home/xin/ArenaSDK_Linux_x64/GenICam/library/CPP/include\



VPATH		=   src:\
	            includes:\
	            main:





LBITS := $(shell getconf LONG_BIT)
ifeq ($(LBITS),64)
	LDFLAGS1= -m64 -Wl,--allow-shlib-undefined,--as-needed
#	LDFLAGS = -pthread -lusrp -lusb
	LDFLAGS = -L$(ARENA_ROOT)/GenICam/library/lib/Linux64_x64/libGCBase_gcc54_v3_3_LUCID.so\
			  -L$(ARENA_ROOT)/GenICam/library/lib/Linux64_x64/libGenApi_gcc54_v3_3_LUCID.so\
			  -L$(ARENA_ROOT)/lib64/libarena.so -L$(ARENA_ROOT)/lib64/libsave.so -L$(ARENA_ROOT)/lib64/libgentl.so
	CFLAGS	= -O2 -D_FORTIFY_SOURCE=0 -g3 -m64 $(CINCPATHFLAGS)
else
	LDFLAGS	= -lpthread -lusrp -m32
	CFLAGS	= -O2 -D_FORTIFY_SOURCE=0 -g3 -m32 $(CINCPATHFLAGS)
endif



SKIP = %main.cpp 
SRCC = $(wildcard main/*.cpp src/*.cpp)
SRC = $(filter-out $(SKIP), $(SRCC)) 
OBJS = $(SRC:.cpp=.o)

HEADERS = $(wildcard includes/*.h)




EXE =	gps-sdr






all: $(EXE)
	@echo ---- Build Complete ----








gps-sdr: main.o $(OBJS) $(DIS) $(HEADERS)
	 $(LINK) $(LDFLAGS1) -o $@ main.o $(OBJS) $(LDFLAGS)




%.o:%.cpp $(HEADERS)
	$(CC) $(CFLAGS) -c $< -o $@ 

%.dis:%.cpp	
	$(CC) $(CFLAGS) -S $< -o $@













clean: distclean

minclean: oclean

oclean:
	@rm -rvf `find . \( -name "*.o" \) -print` 	
	
distclean:
	@rm -rvf `find . \( -name "*.o" -o -name "*.dis" -o -name "*.dat" -o -name "*.klm" -o -name "*.m~" -o -name "*.tlm" -o -name "*.log" -o -name "gps-*" \) -print`
	
